/**
 * Physics Quiz Question Bank — 100 Rigorously Verified Gravitation Questions
 * Aligned with Class 11-12 Physics, JEE Main, and JEE Advanced.
 * 10 Categories × 10 Questions each with full explanations, hints, and concept tags.
 */

export const QUESTION_BANK = [
  // =========================================================================
  // CATEGORY 01: FUNDAMENTAL GRAVITATION (10 Questions)
  // =========================================================================
  {
    id: 'q-fund-01',
    category: 'cat-01',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'What are the SI unit and dimensional formula of the Universal Gravitational Constant G?',
    options: [
      { label: 'A', text: 'N·m²/kg² and [M⁻¹ L³ T⁻²]' },
      { label: 'B', text: 'N·m/kg and [M⁻¹ L² T⁻¹]' },
      { label: 'C', text: 'N·m²/kg and [M L³ T⁻²]' },
      { label: 'D', text: 'N/kg² and [M⁻¹ L³ T⁻¹]' },
    ],
    correctAnswer: 'A',
    hint: 'Rearrange Newton’s formula F = G·m₁·m₂/r² to isolate G = F·r² / (m₁·m₂).',
    explanation: 'From F = G(m₁m₂)/r², G = F·r² / (m₁m₂).\nUnits: N·m²/kg² (or m³·kg⁻¹·s⁻²).\nDimensions: [M L T⁻²] · [L²] / [M²] = [M⁻¹ L³ T⁻²].',
    conceptTested: 'Dimensions and SI units of Universal Gravitational Constant G',
  },
  {
    id: 'q-fund-02',
    category: 'cat-01',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'The value of the universal gravitational constant G was first determined experimentally by which scientist using a torsion balance?',
    options: [
      { label: 'A', text: 'Sir Isaac Newton' },
      { label: 'B', text: 'Henry Cavendish' },
      { label: 'C', text: 'Galileo Galilei' },
      { label: 'D', text: 'Johannes Kepler' },
    ],
    correctAnswer: 'B',
    hint: 'Newton proposed the law, but the numerical value of G was measured over a century later in 1798.',
    explanation: 'Henry Cavendish measured the value of G in 1798 using a sensitive torsion balance apparatus, often referred to as "weighing the Earth".',
    conceptTested: 'Cavendish experimental determination of G',
  },
  {
    id: 'q-fund-03',
    category: 'cat-01',
    examLevel: 'CLASS 11-12',
    difficulty: 'MEDIUM',
    type: 'conceptual',
    question: 'Why is gravitation classified as a "central force"?',
    options: [
      { label: 'A', text: 'Because it originates from the center of the Earth only' },
      { label: 'B', text: 'Because its line of action passes strictly through the centers of mass of the interacting bodies' },
      { label: 'C', text: 'Because it acts only on bodies having spherical geometry' },
      { label: 'D', text: 'Because its magnitude is constant at the center of the orbit' },
    ],
    correctAnswer: 'B',
    hint: 'Consider the definition of central force: torque τ = r⃗ × F⃗ = 0 about the center of mass.',
    explanation: 'A central force acts along the line joining the centers of the two interacting bodies. Consequently, the torque about the center of attraction is zero (τ = r⃗ × F⃗ = 0), ensuring conservation of orbital angular momentum.',
    conceptTested: 'Central force nature and angular momentum conservation',
  },
  {
    id: 'q-fund-04',
    category: 'cat-01',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'If two point masses are immersed in water instead of vacuum, how does the gravitational attraction between them change in classical Newtonian physics?',
    options: [
      { label: 'A', text: 'It decreases due to the dielectric-like screening of water' },
      { label: 'B', text: 'It increases due to the hydrostatic pressure of water' },
      { label: 'C', text: 'It remains completely unchanged' },
      { label: 'D', text: 'It drops to zero' },
    ],
    correctAnswer: 'C',
    hint: 'Unlike electrostatic forces which depend on permittivity ε, does gravity depend on the intervening medium?',
    explanation: 'Gravitational attraction between two masses in classical Newtonian mechanics is completely independent of the intervening physical medium, temperature, or pressure.',
    conceptTested: 'Medium-independence of classical gravitational force',
  },
  {
    id: 'q-fund-05',
    category: 'cat-01',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'What is the order of magnitude of the ratio of gravitational force F_g to electrostatic force F_e between two protons separated by distance r?',
    options: [
      { label: 'A', text: '10⁻¹⁰' },
      { label: 'B', text: '10⁻²⁴' },
      { label: 'C', text: '10⁻³⁶' },
      { label: 'D', text: '10⁻⁴⁵' },
    ],
    correctAnswer: 'C',
    hint: 'Calculate F_g/F_e = (G·m_p²) / (k·e²), where m_p ≈ 1.67×10⁻²⁷ kg and e ≈ 1.6×10⁻¹⁹ C.',
    explanation: 'F_g / F_e = (G · m_p²) / [ (1 / 4πε₀) · e² ]\n= [ (6.67 × 10⁻¹¹) · (1.67 × 10⁻²⁷)² ] / [ (9 × 10⁹) · (1.6 × 10⁻¹⁹)² ]\n≈ 1.86 × 10⁻³⁶ ≈ 10⁻³⁶.\nThis demonstrates that gravity is the weakest fundamental force.',
    conceptTested: 'Relative strength of gravitational vs electrostatic force',
  },
  {
    id: 'q-fund-06',
    category: 'cat-01',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Which of the following properties is strictly FALSE regarding Newtonian gravitational force?',
    options: [
      { label: 'A', text: 'It obeys the inverse-square law (F ∝ 1/r²)' },
      { label: 'B', text: 'It can be repulsive under special geometric orientations' },
      { label: 'C', text: 'It is a conservative force (∮ F⃗·dr⃗ = 0)' },
      { label: 'D', text: 'It constitutes an action-reaction pair obeying Newton’s Third Law' },
    ],
    correctAnswer: 'B',
    hint: 'Do negative gravitational masses or repulsive gravitational forces exist in classical physics?',
    explanation: 'Gravitational force in Newtonian mechanics is strictly attractive. Negative gravitational mass does not exist, so gravitational repulsion is impossible in Newtonian physics.',
    conceptTested: 'Strictly attractive property of gravitation',
  },
  {
    id: 'q-fund-07',
    category: 'cat-01',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'conceptual',
    question: 'The dimensional formula of the ratio G / g (Universal Gravitational Constant divided by surface acceleration due to gravity on Earth) is:',
    options: [
      { label: 'A', text: '[M⁻¹ L² T⁰]' },
      { label: 'B', text: '[M⁻¹ L³ T⁻¹]' },
      { label: 'C', text: '[M⁰ L² T⁻²]' },
      { label: 'D', text: '[M⁻² L² T⁰]' },
    ],
    correctAnswer: 'A',
    hint: 'Substitute [G] = [M⁻¹ L³ T⁻²] and [g] = [L T⁻²].',
    explanation: '[G] = [M⁻¹ L³ T⁻²]\n[g] = [L T⁻²]\n[G / g] = [M⁻¹ L³ T⁻²] / [L T⁻²] = [M⁻¹ L² T⁰].\nNote that from g = GM/R², G/g = R²/M, which directly has dimensions L² / M = [M⁻¹ L²].',
    conceptTested: 'Dimensional analysis of gravitational parameters',
  },
  {
    id: 'q-fund-08',
    category: 'cat-01',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'trap',
    question: 'According to the Weak Equivalence Principle verified by Eötvös and Galileo, which two physical quantities are strictly proportional (or identical):',
    options: [
      { label: 'A', text: 'Inertial mass and gravitational mass' },
      { label: 'B', text: 'Gravitational potential and kinetic energy' },
      { label: 'C', text: 'Universal constant G and local acceleration g' },
      { label: 'D', text: 'Gravitational force and centripetal acceleration' },
    ],
    correctAnswer: 'A',
    hint: 'Why do all bodies fall with the exact same acceleration in vacuum regardless of their mass?',
    explanation: 'From F = m_inertial · a and F = m_grav · g, acceleration is a = (m_grav / m_inertial) · g. Because inertial mass (resistance to acceleration) is identically equal to gravitational mass (response to gravity), all bodies fall at the exact same rate in vacuum.',
    conceptTested: 'Equivalence Principle of inertial and gravitational mass',
  },
  {
    id: 'q-fund-09',
    category: 'cat-01',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Gravitational force between two particles has an effective physical range of:',
    options: [
      { label: 'A', text: 'Nuclear scale (~10⁻¹⁵ m)' },
      { label: 'B', text: 'Atomic scale (~10⁻¹⁰ m)' },
      { label: 'C', text: 'Planetary scale (~10¹⁰ m)' },
      { label: 'D', text: 'Infinite range (F → 0 only as r → ∞)' },
    ],
    correctAnswer: 'D',
    hint: 'Since F ∝ 1/r², at what distance does F strictly become zero?',
    explanation: 'Gravitation is a long-range interaction. Because F ∝ 1/r², the force approaches zero asymptotically only as distance r approaches infinity (F → 0 as r → ∞).',
    conceptTested: 'Infinite range of the inverse-square force',
  },
  {
    id: 'q-fund-10',
    category: 'cat-01',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'conceptual',
    question: 'If the gravitational interaction between two bodies were mediated through an exchange particle having a non-zero rest mass m₀, the force would fall off with distance r according to a Yukawa potential ~ (1/r)·e^(-r/λ). The classical 1/r² law implies that the graviton must have:',
    options: [
      { label: 'A', text: 'Exactly zero rest mass' },
      { label: 'B', text: 'A rest mass equal to that of an electron' },
      { label: 'C', text: 'Negative rest mass' },
      { label: 'D', text: 'Infinite rest mass' },
    ],
    correctAnswer: 'A',
    hint: 'Range λ is related to carrier mass by λ = ħ / (m₀·c). For infinite range, what must m₀ be?',
    explanation: 'For a force to have infinite range and follow a pure inverse-square law (1/r²), the mediating quantum (the hypothetical graviton) must have strictly zero rest mass (m₀ = 0), exactly like the photon in electromagnetism.',
    conceptTested: 'Quantum field theoretical implication of 1/r² force',
  },

  // =========================================================================
  // CATEGORY 02: NEWTON'S UNIVERSAL LAW (10 Questions)
  // =========================================================================
  {
    id: 'q-law-01',
    category: 'cat-02',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'Two point masses m₁ and m₂ attract each other with force F. If both masses are doubled and the separation distance between them is halved, the new force F′ is:',
    options: [
      { label: 'A', text: '2 F' },
      { label: 'B', text: '4 F' },
      { label: 'C', text: '8 F' },
      { label: 'D', text: '16 F' },
    ],
    correctAnswer: 'D',
    hint: 'F′ = G · (2m₁ · 2m₂) / (r / 2)². Calculate the multiplier.',
    explanation: 'F′ = G · (2m₁ · 2m₂) / (r / 2)² = 4 · G(m₁m₂) / (r² / 4) = 4 · 4 · F = 16 F.\nThe gravitational force increases by a factor of 16.',
    conceptTested: 'Scaling of gravitational force with mass and distance',
  },
  {
    id: 'q-law-02',
    category: 'cat-02',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'The Sun exerts a gravitational pull on the Earth. The Earth also exerts a gravitational pull on the Sun. Comparing the magnitudes of these two forces:',
    options: [
      { label: 'A', text: 'The Sun exerts a much larger force because its mass is 333,000 times larger' },
      { label: 'B', text: 'The Earth exerts a larger force due to centripetal reaction' },
      { label: 'C', text: 'Both bodies exert strictly equal forces on each other' },
      { label: 'D', text: 'The ratio of forces depends on the orbital speed' },
    ],
    correctAnswer: 'C',
    hint: 'Recall Newton’s Third Law of Motion (action and reaction).',
    explanation: 'By Newton’s Third Law and Universal Gravitation: F_Sun-Earth = G·M_Sun·M_Earth / r² = F_Earth-Sun. The forces are equal in magnitude and opposite in direction. The Sun experiences a much smaller acceleration solely because of its enormous mass (a = F/M).',
    conceptTested: "Newton's Third Law in gravitational interaction",
  },
  {
    id: 'q-law-03',
    category: 'cat-02',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'Three identical spherical balls, each of mass M and radius R, are placed in mutual contact on a horizontal table. The magnitude of the gravitational attraction on any one ball due to the other two is:',
    options: [
      { label: 'A', text: '√3 · G M² / (4 R²)' },
      { label: 'B', text: 'G M² / (4 R²)' },
      { label: 'C', text: '2 · G M² / (4 R²)' },
      { label: 'D', text: '√2 · G M² / (4 R²)' },
    ],
    correctAnswer: 'A',
    hint: 'Centers form an equilateral triangle of side 2R. The angle between the two forces is 60°. Use vector resultant R = √(F² + F² + 2F²cos60°).',
    explanation: 'Distance between touching centers is r = 2R.\nForce from each neighbor: F = G·M² / (2R)² = G·M² / (4R²).\nThe angle between the two lines of action is 60° (equilateral triangle).\nResultant force: F_net = √(F² + F² + 2F² cos 60°) = √(3F²) = F√3 = √3 · G M² / (4 R²).',
    conceptTested: 'Vector addition of gravitational forces in symmetric geometry',
  },
  {
    id: 'q-law-04',
    category: 'cat-02',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'trap',
    question: 'Two identical lead spheres, each of uniform mass density ρ and radius R, are placed in physical contact with each other. The gravitational force between them is directly proportional to which power of R?',
    options: [
      { label: 'A', text: 'R²' },
      { label: 'B', text: 'R⁴' },
      { label: 'C', text: 'R⁶' },
      { label: 'D', text: '1 / R²' },
    ],
    correctAnswer: 'B',
    hint: 'Mass M is proportional to ρ·R³. Separation between centers is r = 2R. Substitute both into Newton’s law.',
    explanation: 'M = (4/3)π R³ ρ ⟹ M ∝ R³.\nSeparation between touching centers: r = 2R ⟹ r² ∝ R².\nF = G·M² / r² ∝ (R³)² / R² = R⁶ / R² = R⁴.\nTherefore, F is proportional to R⁴.',
    conceptTested: 'Scaling of gravitational attraction between touching spheres with density',
  },
  {
    id: 'q-law-05',
    category: 'cat-02',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'If the distance between two bodies is increased by 100%, the gravitational force between them decreases by what percentage?',
    options: [
      { label: 'A', text: '50%' },
      { label: 'B', text: '75%' },
      { label: 'C', text: '100%' },
      { label: 'D', text: '25%' },
    ],
    correctAnswer: 'B',
    hint: 'Increasing distance by 100% means r′ = r + 1.00r = 2r.',
    explanation: 'r′ = 2r ⟹ F′ = G(m₁m₂) / (2r)² = F / 4 = 0.25 F.\nPercentage decrease = [ (F - F′) / F ] × 100% = [ (F - 0.25F) / F ] × 100% = 75%.',
    conceptTested: 'Inverse-square percentage drop calculation',
  },
  {
    id: 'q-law-06',
    category: 'cat-02',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'A mass M is to be divided into two parts, m and (M - m). For the gravitational force between these two parts at a given separation to be MAXIMUM, the ratio m / M must be:',
    options: [
      { label: 'A', text: '1 / 4' },
      { label: 'B', text: '1 / 2' },
      { label: 'C', text: '1 / 3' },
      { label: 'D', text: '2 / 3' },
    ],
    correctAnswer: 'B',
    hint: 'Maximize the product f(m) = m·(M - m) with respect to m: set df/dm = 0.',
    explanation: 'F = G · m(M - m) / r².\nTo maximize F with respect to m, maximize f(m) = m·M - m².\nd/dm [m·M - m²] = M - 2m = 0 ⟹ m = M / 2.\nThus, m / M = 1/2.',
    conceptTested: 'Extremum condition for gravitational attraction between partitioned mass',
  },
  {
    id: 'q-law-07',
    category: 'cat-02',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'Four identical point masses, each of mass m, are situated at the four vertices of a square of side length a. The net gravitational force on any one mass is directed toward the center of the square with magnitude:',
    options: [
      { label: 'A', text: '(G m² / a²) · [ √2 + 1/2 ]' },
      { label: 'B', text: '(G m² / a²) · [ 2√2 + 1 ]' },
      { label: 'C', text: '(G m² / a²) · [ √2 + 1/4 ]' },
      { label: 'D', text: '(G m² / a²) · [ 2√2 ]' },
    ],
    correctAnswer: 'A',
    hint: 'Two adjacent masses exert force F₁ = Gm²/a² at 90° (resultant √2·F₁ along diagonal). Opposite corner mass is at distance a√2.',
    explanation: 'Adjacent vertices (distance a): Two forces F₁ = Gm²/a² perpendicular to each other. Their vector resultant is F_adj = F₁√2 = √2(Gm²/a²) along the diagonal toward center.\nOpposite vertex (diagonal distance a√2): Force F_diag = Gm² / (a√2)² = Gm² / (2a²) along the exact same diagonal.\nNet force: F_net = F_adj + F_diag = (Gm²/a²) · [ √2 + 1/2 ].',
    conceptTested: 'Superposition of gravitational forces on 2D square lattice',
  },
  {
    id: 'q-law-08',
    category: 'cat-02',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'According to Newton’s Shell Theorem, what is the gravitational force exerted by a uniform spherical shell of mass M on a point mass m placed INSIDE the shell?',
    options: [
      { label: 'A', text: 'G M m / R² directed toward the nearest wall' },
      { label: 'B', text: 'G M m / r² directed toward the center' },
      { label: 'C', text: 'Strictly zero everywhere inside the shell' },
      { label: 'D', text: 'Infinite at the center' },
    ],
    correctAnswer: 'C',
    hint: 'Forces from opposite elements of the spherical shell cancel each other out identically.',
    explanation: 'Newton’s Shell Theorem II states that the gravitational field (and therefore the net force on any mass) anywhere inside a uniform spherical shell is identically zero: F_inside = 0.',
    conceptTested: "Newton's Shell Theorem for hollow spherical shells",
  },
  {
    id: 'q-law-09',
    category: 'cat-02',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'trap',
    question: 'In the vector formulation F⃗₁₂ = - (G m₁ m₂ / r²) · r̂₁₂, what does the unit vector r̂₁₂ represent?',
    options: [
      { label: 'A', text: 'A unit vector pointing from mass 2 toward mass 1' },
      { label: 'B', text: 'A unit vector pointing from mass 1 toward mass 2' },
      { label: 'C', text: 'A vector with magnitude equal to distance r' },
      { label: 'D', text: 'A dimensionless scalar quantity' },
    ],
    correctAnswer: 'B',
    hint: 'r̂₁₂ is defined by (r⃗₂ - r⃗₁) / |r⃗₂ - r⃗₁|, which points from body 1 to body 2.',
    explanation: 'By standard convention, r̂₁₂ is the unit vector pointing from mass 1 toward mass 2 (r̂₁₂ = r⃗₁₂ / r). The minus sign in F⃗₁₂ = -(Gm₁m₂/r²)r̂₁₂ indicates that the force on mass 1 is attractive, pulling it toward mass 2.',
    conceptTested: 'Proper convention and direction of position unit vector in gravitation',
  },
  {
    id: 'q-law-10',
    category: 'cat-02',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'A uniform thin rod of length L and mass M lies along the x-axis from x = 0 to x = L. A point mass m is placed on the axis at x = -d (d > 0). The gravitational attraction between the rod and point mass is:',
    options: [
      { label: 'A', text: 'G M m / d²' },
      { label: 'B', text: 'G M m / (d · (L + d))' },
      { label: 'C', text: 'G M m / (L + d)²' },
      { label: 'D', text: 'G M m / (2 d L)' },
    ],
    correctAnswer: 'B',
    hint: 'Integrate dF = G·m·dm / x² where dm = (M/L)dx and distance varies from d to d + L.',
    explanation: 'Linear mass density λ = M/L. Element at distance x from point mass has mass dm = λ dx.\ndF = G·m·dm / x² = (G m M / L) · (dx / x²).\nIntegrating from x = d to x = d + L:\nF = (G m M / L) · [ -1/x ]_d^(d+L) = (G m M / L) · [ 1/d - 1/(d+L) ]\n= (G m M / L) · [ L / (d(d + L)) ] = G M m / [ d(L + d) ].',
    conceptTested: 'Calculus-based integration of gravitational force for continuous linear mass',
  },

  // =========================================================================
  // CATEGORY 03: ACCELERATION DUE TO GRAVITY (10 Questions)
  // =========================================================================
  {
    id: 'q-acc-01',
    category: 'cat-03',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'At what height h above Earth’s surface does the acceleration due to gravity become g / 4? (Let R be Earth’s radius).',
    options: [
      { label: 'A', text: 'h = R / 2' },
      { label: 'B', text: 'h = R' },
      { label: 'C', text: 'h = 2 R' },
      { label: 'D', text: 'h = 4 R' },
    ],
    correctAnswer: 'B',
    hint: 'Use the exact formula g_h = g · [ R / (R + h) ]² = g / 4. Do not use the linear approximation since h is not small.',
    explanation: 'g_h = g · [ R / (R + h) ]² = g / 4.\nTaking square roots on both sides:\nR / (R + h) = 1 / 2 ⟹ 2R = R + h ⟹ h = R.\nAt height equal to Earth’s radius, gravity drops to one-fourth.',
    conceptTested: 'Exact variation of g with altitude above Earth',
  },
  {
    id: 'q-acc-02',
    category: 'cat-03',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'At what depth d below Earth’s surface is the acceleration due to gravity equal to g / 4? (Assume Earth is a sphere of uniform density).',
    options: [
      { label: 'A', text: 'd = R / 4' },
      { label: 'B', text: 'd = R / 2' },
      { label: 'C', text: 'd = 3 R / 4' },
      { label: 'D', text: 'd = R' },
    ],
    correctAnswer: 'C',
    hint: 'Inside Earth, gravity varies linearly with depth: g_d = g(1 - d / R).',
    explanation: 'g_d = g(1 - d / R) = g / 4 ⟹ 1 - d / R = 1 / 4 ⟹ d / R = 3 / 4 ⟹ d = 3R / 4.\nAt depth of 3/4th Earth radius, gravity is 1/4th of surface gravity.',
    conceptTested: 'Linear variation of acceleration due to gravity with depth',
  },
  {
    id: 'q-acc-03',
    category: 'cat-03',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'For small altitude h ≪ R and small depth d ≪ R, at what height h is the decrease in g the same as that at depth d = 32 km?',
    options: [
      { label: 'A', text: '64 km' },
      { label: 'B', text: '32 km' },
      { label: 'C', text: '16 km' },
      { label: 'D', text: '8 km' },
    ],
    correctAnswer: 'C',
    hint: 'For h ≪ R, Δg_h / g ≈ -2h / R. For depth d, Δg_d / g = -d / R. Equate the two fractional decreases.',
    explanation: 'Fractional change with height: Δg_h / g = 2h / R.\nFractional change with depth: Δg_d / g = d / R.\nEquating both: 2h / R = d / R ⟹ 2h = d ⟹ h = d / 2.\nWith d = 32 km: h = 32 / 2 = 16 km.',
    conceptTested: 'Comparison between rate of decrease of g with height vs depth',
  },
  {
    id: 'q-acc-04',
    category: 'cat-03',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'If Earth shrinks to half its current radius while keeping its mass strictly constant, the new acceleration due to gravity on its surface would become:',
    options: [
      { label: 'A', text: 'g / 2' },
      { label: 'B', text: '2 g' },
      { label: 'C', text: '4 g' },
      { label: 'D', text: 'g / 4' },
    ],
    correctAnswer: 'C',
    hint: 'g = G M / R². Replace R with R/2.',
    explanation: 'g′ = G M / (R / 2)² = G M / (R² / 4) = 4 · (G M / R²) = 4 g.\nSurface gravity quadruples when radius is halved at constant mass.',
    conceptTested: 'Inverse-square dependence of surface gravity on planetary radius',
  },
  {
    id: 'q-acc-05',
    category: 'cat-03',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'In terms of uniform mass density ρ and radius R, surface gravity g is proportional to:',
    options: [
      { label: 'A', text: 'ρ / R' },
      { label: 'B', text: 'ρ · R' },
      { label: 'C', text: 'ρ · R²' },
      { label: 'D', text: 'ρ² · R' },
    ],
    correctAnswer: 'B',
    hint: 'Express mass M as (4/3)πR³ρ and substitute into g = GM/R².',
    explanation: 'g = G M / R² = G · [ (4/3)π R³ ρ ] / R² = (4/3) π G ρ R.\nTherefore, g ∝ ρ · R.',
    conceptTested: 'Planetary surface gravity in terms of mean density and radius',
  },
  {
    id: 'q-acc-06',
    category: 'cat-03',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'With what angular speed ω must Earth rotate about its polar axis so that a body on the equator experiences apparent weightlessness? (Take R = 6400 km, g = 10 m/s²).',
    options: [
      { label: 'A', text: '1.25 × 10⁻³ rad/s' },
      { label: 'B', text: '2.50 × 10⁻³ rad/s' },
      { label: 'C', text: '7.27 × 10⁻⁵ rad/s' },
      { label: 'D', text: '1.25 × 10⁻⁴ rad/s' },
    ],
    correctAnswer: 'A',
    hint: 'At equator (latitude λ = 0), apparent gravity is g_eff = g - ω²R. For weightlessness, set g_eff = 0 ⟹ ω = √(g / R).',
    explanation: 'g_eff = g - ω² R = 0 ⟹ ω = √(g / R).\nω = √(10 / (6.4 × 10⁶)) = √(1.5625 × 10⁻⁶) = 1.25 × 10⁻³ rad/s.\n(This is about 17 times Earth’s present rotation rate of 7.29 × 10⁻⁵ rad/s).',
    conceptTested: 'Centrifugal reduction of effective gravity at equator',
  },
  {
    id: 'q-acc-07',
    category: 'cat-03',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Due to Earth’s rotation and oblateness (equatorial bulge), where on Earth’s surface is the acceleration due to gravity MAXIMUM?',
    options: [
      { label: 'A', text: 'At the Equator' },
      { label: 'B', text: 'At the Tropic of Cancer' },
      { label: 'C', text: 'At the Geographic Poles' },
      { label: 'D', text: 'Identical everywhere on the surface' },
    ],
    correctAnswer: 'C',
    hint: 'At the poles, centrifugal acceleration is zero (cos 90° = 0) and polar radius is shorter than equatorial radius.',
    explanation: 'g_pole > g_equator because:\n1. Centrifugal effect is zero at poles (latitude λ = 90° ⟹ ω²R cos²λ = 0).\n2. Polar radius is ~21 km shorter than equatorial radius (g ∝ 1/R²).\nHence g is maximum at the poles (~9.83 m/s²) and minimum at the equator (~9.78 m/s²).',
    conceptTested: 'Latitude and oblateness dependence of Earth gravity',
  },
  {
    id: 'q-acc-08',
    category: 'cat-03',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'What is the acceleration due to gravity at the exact geometric center of Earth?',
    options: [
      { label: 'A', text: 'Zero' },
      { label: 'B', text: 'Infinite' },
      { label: 'C', text: '9.81 m/s²' },
      { label: 'D', text: 'Equal to universal constant G' },
    ],
    correctAnswer: 'A',
    hint: 'At the center, depth d = R. Substitute into g_d = g(1 - d/R).',
    explanation: 'At Earth’s center, d = R ⟹ g_center = g(1 - R/R) = 0. Symmetrical mass elements from all directions pull outward equally, canceling the net gravitational acceleration.',
    conceptTested: 'Zero gravity at planetary center',
  },
  {
    id: 'q-acc-09',
    category: 'cat-03',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'A planet has radius twice that of Earth (R_p = 2 R_E) and mean density equal to Earth’s density (ρ_p = ρ_E). The surface gravity on this planet g_p compared to Earth’s gravity g_E is:',
    options: [
      { label: 'A', text: 'g_p = g_E / 2' },
      { label: 'B', text: 'g_p = g_E' },
      { label: 'C', text: 'g_p = 2 g_E' },
      { label: 'D', text: 'g_p = 4 g_E' },
    ],
    correctAnswer: 'C',
    hint: 'Recall g = (4/3)π G ρ R. When density is constant, g is directly proportional to radius.',
    explanation: 'Since g ∝ ρ · R and ρ_p = ρ_E:\ng_p / g_E = R_p / R_E = 2.\nTherefore, g_p = 2 g_E.',
    conceptTested: 'Planetary scaling of surface gravity with radius at constant density',
  },
  {
    id: 'q-acc-10',
    category: 'cat-03',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'trap',
    question: 'The percentage decrease in the value of g at a height h above Earth’s surface is 1%. What will be the percentage decrease in g at a depth d = h below Earth’s surface? (Assume h ≪ R).',
    options: [
      { label: 'A', text: '2.0%' },
      { label: 'B', text: '1.0%' },
      { label: 'C', text: '0.5%' },
      { label: 'D', text: '0.25%' },
    ],
    correctAnswer: 'C',
    hint: 'At height h: Δg/g = 2h/R = 1%. What is Δg/g at depth d = h?',
    explanation: 'For h ≪ R: (Δg/g)_height = 2h / R = 1.0% ⟹ h / R = 0.5%.\nAt depth d = h: (Δg/g)_depth = d / R = h / R = 0.5%.\nThe rate of decrease with height is twice that with depth.',
    conceptTested: 'Exact ratio of rate of gravity variation with height vs depth',
  },

  // =========================================================================
  // CATEGORY 04: MASS VS WEIGHT (10 Questions)
  // =========================================================================
  {
    id: 'q-mass-01',
    category: 'cat-04',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'A body has a mass of 60 kg on Earth. When taken to the Moon where acceleration due to gravity is g/6, its mass and weight will be approximately:',
    options: [
      { label: 'A', text: 'Mass = 10 kg, Weight = 98 N' },
      { label: 'B', text: 'Mass = 60 kg, Weight = 98 N' },
      { label: 'C', text: 'Mass = 60 kg, Weight = 588 N' },
      { label: 'D', text: 'Mass = 10 kg, Weight = 588 N' },
    ],
    correctAnswer: 'B',
    hint: 'Does mass change when a body is moved from one celestial body to another?',
    explanation: 'Mass is an invariant intrinsic quantity measuring inertia: m = 60 kg everywhere.\nWeight depends on local gravity: W = m · g_moon = 60 · (9.8 / 6) = 98 N (or 10 kg-wt).',
    conceptTested: 'Invariance of mass vs variation of weight with local gravity',
  },
  {
    id: 'q-mass-02',
    category: 'cat-04',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'A student of mass 50 kg stands on a weighing machine inside an elevator accelerating upward with an acceleration a = g / 2. The reading on the machine is: (Take g = 10 m/s²).',
    options: [
      { label: 'A', text: '250 N' },
      { label: 'B', text: '500 N' },
      { label: 'C', text: '750 N' },
      { label: 'D', text: '1000 N' },
    ],
    correctAnswer: 'C',
    hint: 'Normal reaction for upward acceleration is N = m(g + a).',
    explanation: 'Normal reaction (apparent weight) in an upward accelerating elevator:\nN = m(g + a) = 50 · (10 + 5) = 50 · 15 = 750 N.',
    conceptTested: 'Apparent weight in an accelerating reference frame',
  },
  {
    id: 'q-mass-03',
    category: 'cat-04',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'The supporting cable of an elevator snaps, causing the elevator and its passenger of mass m to fall freely under gravity. The reading on a scale under the passenger’s feet during the fall is:',
    options: [
      { label: 'A', text: 'mg' },
      { label: 'B', text: '2 mg' },
      { label: 'C', text: 'Zero' },
      { label: 'D', text: 'mg / 2' },
    ],
    correctAnswer: 'C',
    hint: 'Both the elevator and passenger accelerate at a = g. Does any normal contact force exist between them?',
    explanation: 'Apparent weight is the normal contact force: N = m(g - a). In free fall, a = g ⟹ N = m(g - g) = 0. The passenger experiences apparent weightlessness.',
    conceptTested: 'Apparent weightlessness in free fall',
  },
  {
    id: 'q-mass-04',
    category: 'cat-04',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'conceptual',
    question: 'A merchant buys a quantity of gold using a spring balance at the equator and sells it using the same spring balance at the north pole. Assuming honest measurements and no cheating:',
    options: [
      { label: 'A', text: 'The merchant gains profit because g_pole > g_equator' },
      { label: 'B', text: 'The merchant suffers a loss because g_pole > g_equator' },
      { label: 'C', text: 'Neither gains nor loses because spring balances measure mass' },
      { label: 'D', text: 'The reading is zero at both locations' },
    ],
    correctAnswer: 'A',
    hint: 'Spring balances measure weight (W = mg), not mass. Does g increase from equator to pole?',
    explanation: 'A spring balance measures weight force W = mg. Since g_pole > g_equator (by about 0.5%), the same mass of gold produces a larger spring deflection at the pole, indicating greater weight. Thus the merchant gains profit.',
    conceptTested: 'Measurement differences between spring balance and beam balance',
  },
  {
    id: 'q-mass-05',
    category: 'cat-04',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'An equal-arm pan balance (beam balance) is used to measure the mass of a gold coin on the Moon using calibrated standard gram weights. The reading obtained on the Moon will be:',
    options: [
      { label: 'A', text: '1/6th of the reading obtained on Earth' },
      { label: 'B', text: '6 times the reading obtained on Earth' },
      { label: 'C', text: 'Identical to the reading obtained on Earth' },
      { label: 'D', text: 'Zero because weights float on the Moon' },
    ],
    correctAnswer: 'C',
    hint: 'Beam balance compares mg_coin against m_std·g. Does g cancel out on both sides?',
    explanation: 'An equal-arm beam balance compares forces: m_coin·g = m_std·g ⟹ m_coin = m_std. Because local gravity g acts equally on both pans, it cancels out completely. Hence, a beam balance measures true invariant mass.',
    conceptTested: 'Beam balance measurement principle',
  },
  {
    id: 'q-mass-06',
    category: 'cat-04',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'trap',
    question: 'An astronaut inside the International Space Station (orbiting 400 km above Earth) floats in apparent weightlessness. Which statement correctly explains this phenomenon?',
    options: [
      { label: 'A', text: 'Earth’s gravitational pull is zero at that altitude' },
      { label: 'B', text: 'Centrifugal force cancels Earth’s gravity, making net force zero' },
      { label: 'C', text: 'Both astronaut and station are in continuous free fall towards Earth at the same rate' },
      { label: 'D', text: 'Space station is beyond Earth’s atmosphere' },
    ],
    correctAnswer: 'C',
    hint: 'At h = 400 km, Earth gravity is still ~89% of surface gravity (g ≈ 8.7 m/s²). Why does the astronaut float?',
    explanation: 'At 400 km, gravity is very strong (g ≈ 8.7 m/s²). Both the spacecraft and astronaut are falling freely around Earth with the exact same acceleration. Because there is no relative acceleration, no normal contact force N exists between the astronaut and the floor.',
    conceptTested: 'Physical origin of weightlessness in circular orbit',
  },
  {
    id: 'q-mass-07',
    category: 'cat-04',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'A test object has mass m = 50 kg. On Jupiter, where surface gravity is g = 24.79 m/s², what is the weight of the test object?',
    options: [
      { label: 'A', text: '490.5 N' },
      { label: 'B', text: '1239.5 N' },
      { label: 'C', text: '2479.0 N' },
      { label: 'D', text: '50.0 N' },
    ],
    correctAnswer: 'B',
    hint: 'Use W = m · g with m = 50 kg and g = 24.79 m/s².',
    explanation: 'W = m · g = 50 kg × 24.79 m/s² = 1239.5 N.\n(On Earth, this same 50 kg object weighs 490.5 N).',
    conceptTested: 'Numerical calculation of weight on different planetary bodies',
  },
  {
    id: 'q-mass-08',
    category: 'cat-04',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'A man of mass 70 kg stands in an elevator that accelerates downwards with an acceleration a = 12 m/s² (greater than g = 10 m/s²). What is the force exerted by the man on the ceiling of the elevator?',
    options: [
      { label: 'A', text: 'Zero' },
      { label: 'B', text: '140 N' },
      { label: 'C', text: '700 N' },
      { label: 'D', text: '840 N' },
    ],
    correctAnswer: 'B',
    hint: 'Since a > g, the elevator accelerates downward faster than free fall. The ceiling presses against the man with force N = m(a - g).',
    explanation: 'Equation of motion taking downward as positive:\nmg + N_ceiling = m · a\nN_ceiling = m(a - g) = 70 · (12 - 10) = 70 · 2 = 140 N.\nThe man presses against the ceiling with 140 N.',
    conceptTested: 'Elevator accelerating downwards with acceleration exceeding g',
  },
  {
    id: 'q-mass-09',
    category: 'cat-04',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Which instrument measures mass, and which instrument measures weight?',
    options: [
      { label: 'A', text: 'Spring balance measures mass; beam balance measures weight' },
      { label: 'B', text: 'Beam balance measures mass; spring balance measures weight' },
      { label: 'C', text: 'Both measure mass only' },
      { label: 'D', text: 'Both measure weight only' },
    ],
    correctAnswer: 'B',
    hint: 'A beam balance balances gravitational forces on two pans. A spring balance measures extension due to force.',
    explanation: 'A beam balance compares an unknown mass against standard masses (gravity cancels out, measuring mass). A spring balance measures the restoring spring force F = kx balancing gravity (measuring weight W = mg).',
    conceptTested: 'Measurement distinction between beam balance and spring balance',
  },
  {
    id: 'q-mass-10',
    category: 'cat-04',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'conceptual',
    question: 'What happens to the mass and weight of an iron sphere if it is transported to the center of the Earth?',
    options: [
      { label: 'A', text: 'Mass becomes zero; weight remains constant' },
      { label: 'B', text: 'Both mass and weight become zero' },
      { label: 'C', text: 'Mass remains unchanged; weight becomes zero' },
      { label: 'D', text: 'Both mass and weight remain unchanged' },
    ],
    correctAnswer: 'C',
    hint: 'At Earth’s center, g = 0. What is W = m·g?',
    explanation: 'Mass is the amount of matter in the body and remains strictly invariant (m = constant). Because g = 0 at Earth’s center, weight W = m · 0 = 0.',
    conceptTested: 'Zero weight at planetary center with invariant mass',
  },

  // =========================================================================
  // CATEGORY 05: GRAVITATIONAL FIELD (10 Questions)
  // =========================================================================
  {
    id: 'q-field-01',
    category: 'cat-05',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Gravitational field intensity g⃗ at a point in space is formally defined as:',
    options: [
      { label: 'A', text: 'The gravitational force experienced per unit test mass at that point (g⃗ = F⃗ / m)' },
      { label: 'B', text: 'The potential energy stored per unit mass at that point' },
      { label: 'C', text: 'The work done in shifting a unit mass to infinity' },
      { label: 'D', text: 'The universal gravitational constant G divided by distance' },
    ],
    correctAnswer: 'A',
    hint: 'Compare with electric field intensity E⃗ = F⃗ / q.',
    explanation: 'Gravitational field intensity g⃗ is defined as the gravitational force exerted per unit positive test mass placed at that point: g⃗ = lim(m→0) F⃗ / m. Its SI unit is N/kg or m/s².',
    conceptTested: 'Definition and SI units of gravitational field intensity vector',
  },
  {
    id: 'q-field-02',
    category: 'cat-05',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'In the formula for the gravitational field of a point mass M, g⃗ = - (G M / r²) · r̂, what is the physical meaning of the negative sign?',
    options: [
      { label: 'A', text: 'Field intensity magnitude is a negative scalar' },
      { label: 'B', text: 'The field vector points radially inward toward the source mass M' },
      { label: 'C', text: 'Gravitational potential is zero' },
      { label: 'D', text: 'Gravitational mass is negative' },
    ],
    correctAnswer: 'B',
    hint: 'By convention, unit vector r̂ points outward from M. What direction does -r̂ point?',
    explanation: 'The outward radial unit vector is r̂. Because gravity is strictly attractive, the field line pulls inward toward the mass M. Hence, -r̂ points radially inward toward source mass M.',
    conceptTested: 'Vector direction of gravitational field and negative sign meaning',
  },
  {
    id: 'q-field-03',
    category: 'cat-05',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'Two point masses M and 4M are held fixed at distance d apart. At what distance x from mass M on the line joining them is the net gravitational field ZERO?',
    options: [
      { label: 'A', text: 'x = d / 2' },
      { label: 'B', text: 'x = d / 3' },
      { label: 'C', text: 'x = d / 4' },
      { label: 'D', text: 'x = 2 d / 3' },
    ],
    correctAnswer: 'B',
    hint: 'Equate field magnitudes: G·M / x² = G·(4M) / (d - x)². Take square roots.',
    explanation: 'G M / x² = G (4M) / (d - x)²\n1 / x² = 4 / (d - x)²\nTaking square root: 1 / x = 2 / (d - x) ⟹ d - x = 2x ⟹ 3x = d ⟹ x = d / 3.\nAt d/3 from M, the opposing fields cancel out completely.',
    conceptTested: 'Neutral point calculation between two unequal point masses',
  },
  {
    id: 'q-field-04',
    category: 'cat-05',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Inside a uniform hollow spherical shell of mass M and radius R, what is the gravitational field intensity at a distance r < R from the center?',
    options: [
      { label: 'A', text: 'Zero everywhere' },
      { label: 'B', text: 'G M / r²' },
      { label: 'C', text: 'G M / R²' },
      { label: 'D', text: 'G M r / R³' },
    ],
    correctAnswer: 'A',
    hint: 'Recall Shell Theorem II for interior points.',
    explanation: 'Inside a uniform spherical shell, the gravitational field intensity is identically zero everywhere (g_inside = 0).',
    conceptTested: 'Zero gravitational field inside a uniform spherical shell',
  },
  {
    id: 'q-field-05',
    category: 'cat-05',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'conceptual',
    question: 'For a solid uniform sphere of mass M and radius R, how does gravitational field intensity g vary with distance r from the center for r < R (inside the sphere)?',
    options: [
      { label: 'A', text: 'g ∝ 1 / r²' },
      { label: 'B', text: 'g ∝ 1 / r' },
      { label: 'C', text: 'g ∝ r (linear increase from center to surface)' },
      { label: 'D', text: 'g = 0 everywhere inside' },
    ],
    correctAnswer: 'C',
    hint: 'Only mass enclosed inside sphere of radius r contributes to the field: M_enclosed = M·(r/R)³.',
    explanation: 'By Shell Theorem, outer shell elements exert zero net force. The enclosed mass is M_enc = M · (r³ / R³).\ng(r) = G M_enc / r² = G [ M r³ / R³ ] / r² = (G M / R³) · r.\nHence, g varies linearly with r (g ∝ r) from 0 at center to GM/R² at the surface.',
    conceptTested: 'Interior gravitational field of a uniform solid sphere',
  },
  {
    id: 'q-field-06',
    category: 'cat-05',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Which of the following statements regarding gravitational field lines is FALSE?',
    options: [
      { label: 'A', text: 'They point in the direction of the gravitational field intensity' },
      { label: 'B', text: 'They can form closed loops' },
      { label: 'C', text: 'The density of field lines represents the field strength' },
      { label: 'D', text: 'Two field lines can never intersect' },
    ],
    correctAnswer: 'B',
    hint: 'Is gravity a conservative force? Can a conservative field have closed field lines?',
    explanation: 'Gravitational field is conservative: work done along any closed path is zero (∮ g⃗·dr⃗ = 0). If field lines formed closed loops, a mass moving along that loop would experience continuous positive work, violating conservation of energy.',
    conceptTested: 'Properties of gravitational field lines and conservative fields',
  },
  {
    id: 'q-field-07',
    category: 'cat-05',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'Two point masses, each of mass m, are fixed at coordinates (-a, 0) and (a, 0). The gravitational field intensity at the origin (0, 0) is:',
    options: [
      { label: 'A', text: 'Zero' },
      { label: 'B', text: '2 G m / a² along +x' },
      { label: 'C', text: '2 G m / a² along -x' },
      { label: 'D', text: 'G m / a² along +y' },
    ],
    correctAnswer: 'A',
    hint: 'Add the two field vectors: g⃗₁ pulls toward (-a, 0) and g⃗₂ pulls toward (+a, 0).',
    explanation: 'Field from left mass: g⃗₁ = -(Gm/a²) î (pulls left).\nField from right mass: g⃗₂ = +(Gm/a²) î (pulls right).\nNet field: g⃗_net = g⃗₁ + g⃗₂ = 0.',
    conceptTested: 'Vector cancellation of gravitational fields at symmetric midpoint',
  },
  {
    id: 'q-field-08',
    category: 'cat-05',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'In the previous problem (masses m at (-a, 0) and (a, 0)), what is the magnitude of the gravitational field intensity at point (0, y) on the y-axis?',
    options: [
      { label: 'A', text: '2 G m y / (a² + y²)^(3/2)' },
      { label: 'B', text: '2 G m / (a² + y²)' },
      { label: 'C', text: 'G m y / (a² + y²)' },
      { label: 'D', text: 'Zero' },
    ],
    correctAnswer: 'A',
    hint: 'Horizontal components cancel. Vertical components add: g_net = 2·g·cosθ where cosθ = y / √(a² + y²).',
    explanation: 'Distance r = √(a² + y²).\nField from each mass: g₁ = Gm / (a² + y²).\nHorizontal components cancel by symmetry.\nVertical component: g_y = 2 · g₁ · cosθ = 2 · [ Gm / (a² + y²) ] · [ y / √(a² + y²) ] = 2 G m y / (a² + y²)^(3/2).',
    conceptTested: 'Field resolution and superposition on perpendicular bisector',
  },
  {
    id: 'q-field-09',
    category: 'cat-05',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'trap',
    question: 'The relationship between gravitational field intensity vector g⃗ and gravitational potential V is given by:',
    options: [
      { label: 'A', text: 'g⃗ = +∇V' },
      { label: 'B', text: 'g⃗ = -∇V = -[ (∂V/∂x)î + (∂V/∂y)ĵ + (∂V/∂z)k̂ ]' },
      { label: 'C', text: 'g⃗ = ∇ × V' },
      { label: 'D', text: 'g⃗ = V / r' },
    ],
    correctAnswer: 'B',
    hint: 'Conservative forces are negative gradients of potential energy: F⃗ = -∇U. Since g⃗ = F⃗/m and V = U/m...',
    explanation: 'g⃗ = -∇V = - [ (∂V/∂x) î + (∂V/∂y) ĵ + (∂V/∂z) k̂ ]. The negative sign indicates that the field points in the direction of maximum decrease of gravitational potential.',
    conceptTested: 'Differential relation between gravitational field and potential gradient',
  },
  {
    id: 'q-field-10',
    category: 'cat-05',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'At what value of y on the perpendicular bisector is the gravitational field in question q-field-08 (g_net = 2Gmy / (a² + y²)^(3/2)) a MAXIMUM?',
    options: [
      { label: 'A', text: 'y = a' },
      { label: 'B', text: 'y = a / √2' },
      { label: 'C', text: 'y = a / 2' },
      { label: 'D', text: 'y = a√2' },
    ],
    correctAnswer: 'B',
    hint: 'Differentiate g_net with respect to y and set dg_net / dy = 0.',
    explanation: 'To maximize f(y) = y / (a² + y²)^(3/2):\nf′(y) = [ (a² + y²)^(3/2) - y · (3/2)(a² + y²)^(1/2) · 2y ] / (a² + y³)^3 = 0\n(a² + y²) - 3y² = 0 ⟹ a² - 2y² = 0 ⟹ y = a / √2.',
    conceptTested: 'Maximization of gravitational field along axis of symmetry',
  },

  // =========================================================================
  // CATEGORY 06: GRAVITATIONAL POTENTIAL & POTENTIAL ENERGY (10 Questions)
  // =========================================================================
  {
    id: 'q-pot-01',
    category: 'cat-06',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Gravitational potential V at distance r from a point mass M is given by V = -GM / r. Why is this quantity always negative (with V(∞) = 0)?',
    options: [
      { label: 'A', text: 'Because mass is positive and distance is negative' },
      { label: 'B', text: 'Because work is done by the attractive field in bringing mass from infinity, lowering the system energy' },
      { label: 'C', text: 'Because universal constant G is negative' },
      { label: 'D', text: 'Due to kinetic energy loss' },
    ],
    correctAnswer: 'B',
    hint: 'Gravity does positive work when a mass moves closer from infinity, so potential energy becomes lower than 0.',
    explanation: 'With reference V(∞) = 0, the attractive field pulls the unit mass inward from infinity, doing positive work. An external agent must do negative work to bring it without acceleration. Hence V = -GM/r is negative for all finite separations.',
    conceptTested: 'Physical origin of negative sign in gravitational potential',
  },
  {
    id: 'q-pot-02',
    category: 'cat-06',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'What is the work done by an external agent to slowly lift a body of mass m from Earth’s surface (radius R) to an altitude h = R above the surface?',
    options: [
      { label: 'A', text: 'm g R' },
      { label: 'B', text: '1/2 m g R' },
      { label: 'C', text: '2 m g R' },
      { label: 'D', text: '1/4 m g R' },
    ],
    correctAnswer: 'B',
    hint: 'W = ΔU = U(2R) - U(R). Note that U(r) = -GMm/r and GM/R² = g.',
    explanation: 'U_initial = -GMm / R\nU_final = -GMm / (R + R) = -GMm / (2R)\nW = U_final - U_initial = -GMm/(2R) - (-GMm/R) = GMm / (2R).\nSince GM/R = gR, W = 1/2 m g R.',
    conceptTested: 'Work done in raising a mass to significant altitude',
  },
  {
    id: 'q-pot-03',
    category: 'cat-06',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'conceptual',
    question: 'Inside a uniform hollow spherical shell of mass M and radius R, what is the gravitational potential V at distance r < R from the center?',
    options: [
      { label: 'A', text: 'Zero' },
      { label: 'B', text: '- G M / r' },
      { label: 'C', text: '- G M / R (constant everywhere inside)' },
      { label: 'D', text: '- 3/2 G M / R' },
    ],
    correctAnswer: 'C',
    hint: 'Since g_inside = -dV/dr = 0, V must be constant. What is the value at the surface?',
    explanation: 'Inside the shell, field g = 0 ⟹ dV/dr = 0 ⟹ V = constant. Because potential is continuous at r = R, V_inside = V_surface = -GM/R everywhere inside the shell.',
    conceptTested: 'Uniform gravitational potential inside a spherical shell',
  },
  {
    id: 'q-pot-04',
    category: 'cat-06',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'For a solid uniform sphere of mass M and radius R, the gravitational potential at its exact center V_center compared to surface potential V_surface is:',
    options: [
      { label: 'A', text: 'V_center = V_surface' },
      { label: 'B', text: 'V_center = 1.5 · V_surface' },
      { label: 'C', text: 'V_center = 2 · V_surface' },
      { label: 'D', text: 'V_center = 0' },
    ],
    correctAnswer: 'B',
    hint: 'Integrate dV = -g·dr from surface to center where g(r) = (GM/R³)r.',
    explanation: 'V_center - V_surface = - ∫_R^0 g(r) dr = ∫_0^R (GM/R³)r dr = (GM/R³) · (R²/2) = GM / (2R).\nV_center = V_surface - GM / (2R) = -GM/R - GM/(2R) = - 3/2 (GM / R) = 1.5 · V_surface.',
    conceptTested: 'Gravitational potential at the center of a uniform solid sphere',
  },
  {
    id: 'q-pot-05',
    category: 'cat-06',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'What is the work done in moving a mass m along an equipotential surface of potential V = -50 J/kg through a distance of 10 meters?',
    options: [
      { label: 'A', text: '-500 J' },
      { label: 'B', text: '500 J' },
      { label: 'C', text: 'Strictly Zero' },
      { label: 'D', text: 'Depends on the path taken' },
    ],
    correctAnswer: 'C',
    hint: 'W = m · ΔV. On an equipotential surface, what is ΔV?',
    explanation: 'By definition, potential V is identical everywhere on an equipotential surface (ΔV = 0). Work done is W = m · ΔV = m · 0 = 0.',
    conceptTested: 'Zero work on an equipotential surface',
  },
  {
    id: 'q-pot-06',
    category: 'cat-06',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'Three identical point masses, each of mass m, are situated at the vertices of an equilateral triangle of side length a. The total gravitational potential energy of the system is:',
    options: [
      { label: 'A', text: '- G m² / a' },
      { label: 'B', text: '- 2 G m² / a' },
      { label: 'C', text: '- 3 G m² / a' },
      { label: 'D', text: '- 6 G m² / a' },
    ],
    correctAnswer: 'C',
    hint: 'Number of unique interaction pairs for n = 3 particles is n(n-1)/2 = 3.',
    explanation: 'Number of pairs = ³C₂ = 3.\nU_total = U₁₂ + U₂₃ + U₃₁ = 3 · (-G m² / a) = -3 G m² / a.',
    conceptTested: 'Potential energy of a discrete multi-particle gravitational system',
  },
  {
    id: 'q-pot-07',
    category: 'cat-06',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'The gravitational potential in a region is given by V(x, y, z) = (3x - 4y + 12z) J/kg. What is the magnitude of the gravitational field intensity |g⃗| at the point (1, 1, 1)?',
    options: [
      { label: 'A', text: '13 N/kg' },
      { label: 'B', text: '11 N/kg' },
      { label: 'C', text: '√169 N/kg' },
      { label: 'D', text: '5 N/kg' },
    ],
    correctAnswer: 'A',
    hint: 'g_x = -∂V/∂x, g_y = -∂V/∂y, g_z = -∂V/∂z. Then |g⃗| = √(gx² + gy² + gz²).',
    explanation: 'g_x = -∂V/∂x = -3\ng_y = -∂V/∂y = -(-4) = 4\ng_z = -∂V/∂z = -12\n|g⃗| = √((-3)² + 4² + (-12)²) = √(9 + 16 + 144) = √169 = 13 N/kg.',
    conceptTested: 'Field magnitude calculation from 3D scalar potential function',
  },
  {
    id: 'q-pot-08',
    category: 'cat-06',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'A body of mass m is projected vertically upward from Earth’s surface with initial speed v = √(gR). What is the maximum height h reached above the surface? (Let R be Earth’s radius).',
    options: [
      { label: 'A', text: 'h = R / 2' },
      { label: 'B', text: 'h = R' },
      { label: 'C', text: 'h = 2 R' },
      { label: 'D', text: 'h = 4 R' },
    ],
    correctAnswer: 'B',
    hint: 'Use conservation of mechanical energy: 1/2 m v² - GMm/R = -GMm/(R+h). Remember GM = gR².',
    explanation: '1/2 m (gR) - GMm / R = - GMm / (R + h)\n1/2 (gR) - gR = - gR² / (R + h)\n- 1/2 gR = - gR² / (R + h) ⟹ 1/2 = R / (R + h) ⟹ R + h = 2R ⟹ h = R.\nThe body reaches a height equal to Earth’s radius.',
    conceptTested: 'Energy conservation for vertical projectile reaching astronomical height',
  },
  {
    id: 'q-pot-09',
    category: 'cat-06',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Equipotential surfaces due to an isolated point mass M are:',
    options: [
      { label: 'A', text: 'Concentric spheres centered on mass M' },
      { label: 'B', text: 'Parallel planes perpendicular to the radial direction' },
      { label: 'C', text: 'Concentric cylinders centered on mass M' },
      { label: 'D', text: 'Paraboloids of revolution' },
    ],
    correctAnswer: 'A',
    hint: 'Since V = -GM/r, V is constant wherever r is constant.',
    explanation: 'Because gravitational potential V = -GM/r depends only on radial distance r, points of equal potential form concentric spherical surfaces centered on mass M.',
    conceptTested: 'Geometric shape of equipotential surfaces for spherical symmetry',
  },
  {
    id: 'q-pot-10',
    category: 'cat-06',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'trap',
    question: 'Four particles each of mass m are located at the corners of a square of side a. What is the total energy required to completely disperse this system to infinite separation?',
    options: [
      { label: 'A', text: '(G m² / a) · [ 4 + √2 ]' },
      { label: 'B', text: '(G m² / a) · [ 2 + 2√2 ]' },
      { label: 'C', text: '(G m² / a) · [ 4 + 1/√2 ]' },
      { label: 'D', text: '4 G m² / a' },
    ],
    correctAnswer: 'A',
    hint: 'Total pairs = ⁴C₂ = 6 pairs: 4 along sides (distance a) and 2 along diagonals (distance a√2). Dispersal energy is -U_total.',
    explanation: 'Pairs along sides: 4 pairs at separation a ⟹ U_side = 4 · (-Gm²/a).\nPairs along diagonals: 2 pairs at separation a√2 ⟹ U_diag = 2 · (-Gm²/(a√2)) = -√2(Gm²/a).\nU_total = - (Gm²/a) [ 4 + √2 ].\nEnergy required to disperse to infinity (Binding Energy) = -U_total = (Gm²/a) [ 4 + √2 ].',
    conceptTested: 'Binding energy and total assembly potential energy of 4-body system',
  },

  // =========================================================================
  // CATEGORY 07: ESCAPE VELOCITY (10 Questions)
  // =========================================================================
  {
    id: 'q-esc-01',
    category: 'cat-07',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'The escape velocity from Earth’s surface is approximately:',
    options: [
      { label: 'A', text: '7.92 km/s' },
      { label: 'B', text: '9.81 km/s' },
      { label: 'C', text: '11.2 km/s' },
      { label: 'D', text: '24.8 km/s' },
    ],
    correctAnswer: 'C',
    hint: 'v_e = √(2 g R) with g ≈ 9.8 m/s² and R ≈ 6.4 × 10⁶ m.',
    explanation: 'v_e = √(2 · 9.8 · 6.4 × 10⁶) = √(1.2544 × 10⁸) ≈ 11.2 × 10³ m/s = 11.2 km/s.',
    conceptTested: 'Standard numerical value of Earth escape velocity',
  },
  {
    id: 'q-esc-02',
    category: 'cat-07',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'A projectile has an escape velocity of 11.2 km/s when fired vertically upward. If the same projectile is fired at an angle of 45° to the horizontal, its escape velocity will be:',
    options: [
      { label: 'A', text: '11.2 / √2 km/s' },
      { label: 'B', text: '11.2 · √2 km/s' },
      { label: 'C', text: '11.2 km/s' },
      { label: 'D', text: 'Zero' },
    ],
    correctAnswer: 'C',
    hint: 'Does kinetic energy 1/2 m v² depend on the direction of the velocity vector?',
    explanation: 'Escape velocity is a scalar threshold derived from total energy conservation: 1/2 m v_e² - GMm/R = 0 ⟹ v_e = √(2GM/R). Because kinetic energy is scalar and independent of direction, escape velocity is completely independent of the angle of projection (neglecting atmospheric resistance).',
    conceptTested: 'Direction independence of escape velocity',
  },
  {
    id: 'q-esc-03',
    category: 'cat-07',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'How does the escape velocity of a body depend on its own mass m?',
    options: [
      { label: 'A', text: 'v_e ∝ m' },
      { label: 'B', text: 'v_e ∝ √m' },
      { label: 'C', text: 'v_e is completely independent of the mass of the projectile (m⁰)' },
      { label: 'D', text: 'v_e ∝ 1 / m' },
    ],
    correctAnswer: 'C',
    hint: 'Look at the formula v_e = √(2GM/R). Does m appear in the equation?',
    explanation: 'In 1/2 m v_e² = GMm / R, mass m cancels out on both sides, giving v_e = √(2GM/R). A tiny dust speck and a massive spacecraft require the exact same escape speed.',
    conceptTested: 'Mass independence of the escaping projectile',
  },
  {
    id: 'q-esc-04',
    category: 'cat-07',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'A hypothetical planet has mass twice that of Earth (M_p = 2 M_E) and radius half that of Earth (R_p = R_E / 2). The escape velocity from this planet is:',
    options: [
      { label: 'A', text: '11.2 km/s' },
      { label: 'B', text: '22.4 km/s' },
      { label: 'C', text: '44.8 km/s' },
      { label: 'D', text: '5.6 km/s' },
    ],
    correctAnswer: 'B',
    hint: 'v_e ∝ √(M / R). Calculate the ratio √(M_p/R_p) / √(M_E/R_E).',
    explanation: 'v_e ∝ √(M / R)\nv_p / v_E = √[ (2 M_E / (R_E / 2)) / (M_E / R_E) ] = √(4) = 2.\nv_p = 2 · 11.2 km/s = 22.4 km/s.',
    conceptTested: 'Planetary scaling of escape velocity with mass and radius',
  },
  {
    id: 'q-esc-05',
    category: 'cat-07',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'The mathematical relation between escape velocity v_e from Earth’s surface and orbital velocity v_o of a satellite revolving very close to Earth’s surface is:',
    options: [
      { label: 'A', text: 'v_e = v_o / √2' },
      { label: 'B', text: 'v_e = √2 · v_o' },
      { label: 'C', text: 'v_e = 2 · v_o' },
      { label: 'D', text: 'v_e = v_o²' },
    ],
    correctAnswer: 'B',
    hint: 'Compare v_e = √(2gR) with v_o = √(gR).',
    explanation: 'v_e = √(2GM/R) and v_o = √(GM/R).\nTherefore, v_e = √2 · v_o ≈ 1.414 · v_o.\nTo escape orbit, a satellite must increase its speed by (√2 - 1) ≈ 41.4%.',
    conceptTested: 'Exact ratio between escape velocity and orbital velocity',
  },
  {
    id: 'q-esc-06',
    category: 'cat-07',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Why does the Moon have no permanent atmosphere?',
    options: [
      { label: 'A', text: 'Because temperatures on the Moon are too cold for gases to exist' },
      { label: 'B', text: 'Because root-mean-square thermal speed of gas molecules exceeds Moon’s escape velocity' },
      { label: 'C', text: 'Because Moon has no magnetic poles' },
      { label: 'D', text: 'Because solar radiation creates infinite tidal forces' },
    ],
    correctAnswer: 'B',
    hint: 'Escape velocity on Moon is very small (~2.38 km/s) due to its smaller mass and radius.',
    explanation: 'The escape velocity on Moon is only ~2.38 km/s. The thermal root-mean-square velocity v_rms = √(3kT/m) of common atmospheric gases (oxygen, nitrogen, hydrogen) easily exceeds this escape threshold during lunar daytime, allowing gases to escape into space.',
    conceptTested: 'Kinetic theory criteria for atmospheric retention on celestial bodies',
  },
  {
    id: 'q-esc-07',
    category: 'cat-07',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'If Earth’s radius shrinks by 2% while its mass remains constant, the escape velocity from its surface will change by approximately:',
    options: [
      { label: 'A', text: 'Increase by 1%' },
      { label: 'B', text: 'Decrease by 1%' },
      { label: 'C', text: 'Increase by 2%' },
      { label: 'D', text: 'Decrease by 2%' },
    ],
    correctAnswer: 'A',
    hint: 'v_e ∝ R^(-1/2). Differentiate: Δv_e / v_e = - 1/2 · (ΔR / R).',
    explanation: 'v_e = (2GM)^(1/2) · R^(-1/2).\nFractional change: Δv_e / v_e = - 1/2 · (ΔR / R).\nGiven ΔR / R = -2% (shrinking):\nΔv_e / v_e = - 1/2 · (-2%) = + 1%.\nEscape velocity increases by 1%.',
    conceptTested: 'Fractional and percentage error calculus in escape velocity',
  },
  {
    id: 'q-esc-08',
    category: 'cat-07',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'What is the escape velocity from a point located at an altitude h = 3 R above Earth’s surface? (v_e is surface escape velocity).',
    options: [
      { label: 'A', text: 'v_e / 4' },
      { label: 'B', text: 'v_e / 2' },
      { label: 'C', text: 'v_e / √3' },
      { label: 'D', text: 'v_e / 3' },
    ],
    correctAnswer: 'B',
    hint: 'Distance from center is r = R + h = R + 3R = 4R. Escape speed from radius r is √(2GM/r).',
    explanation: 'r = R + 3R = 4R.\nv_e(r) = √(2GM / r) = √(2GM / 4R) = 1/2 · √(2GM / R) = v_e / 2.',
    conceptTested: 'Escape velocity from points above planetary surface',
  },
  {
    id: 'q-esc-09',
    category: 'cat-07',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'trap',
    question: 'A body is projected from Earth’s surface with a speed equal to twice the escape velocity (v = 2 v_e). What is its speed v_∞ when it has escaped completely to infinity?',
    options: [
      { label: 'A', text: 'v_∞ = v_e' },
      { label: 'B', text: 'v_∞ = √3 · v_e' },
      { label: 'C', text: 'v_∞ = 2 v_e' },
      { label: 'D', text: 'v_∞ = 3 v_e' },
    ],
    correctAnswer: 'B',
    hint: 'Total energy conservation: 1/2 m v² - GMm/R = 1/2 m v_∞² + 0. Remember GMm/R = 1/2 m v_e².',
    explanation: '1/2 m v² - 1/2 m v_e² = 1/2 m v_∞²\nv_∞² = v² - v_e² = (2 v_e)² - v_e² = 4 v_e² - v_e² = 3 v_e²\nv_∞ = √3 · v_e ≈ 1.732 · (11.2 km/s) ≈ 19.4 km/s.',
    conceptTested: 'Residual velocity of hyperbolic escape trajectory at infinity',
  },
  {
    id: 'q-esc-10',
    category: 'cat-07',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'Black holes have an escape velocity equal to the speed of light c. The Schwarzschild radius R_s of a non-rotating mass M is given by:',
    options: [
      { label: 'A', text: 'R_s = G M / c²' },
      { label: 'B', text: 'R_s = 2 G M / c²' },
      { label: 'C', text: 'R_s = G M / (2 c²)' },
      { label: 'D', text: 'R_s = 4 G M / c²' },
    ],
    correctAnswer: 'B',
    hint: 'Set escape velocity formula v_e = √(2GM/R) equal to c and solve for R.',
    explanation: 'c = √(2GM / R_s) ⟹ c² = 2GM / R_s ⟹ R_s = 2GM / c².\nFor Earth (M ≈ 6×10²⁴ kg), R_s ≈ 9 mm. For Sun, R_s ≈ 3 km.',
    conceptTested: 'Relativistic Schwarzschild radius derivation from escape threshold',
  },

  // =========================================================================
  // CATEGORY 08: SATELLITES & ORBITAL MECHANICS (10 Questions)
  // =========================================================================
  {
    id: 'q-sat-01',
    category: 'cat-08',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'The orbital velocity of a satellite revolving in a circular orbit very close to Earth’s surface (r ≈ R) is approximately:',
    options: [
      { label: 'A', text: '7.92 km/s' },
      { label: 'B', text: '11.2 km/s' },
      { label: 'C', text: '9.81 km/s' },
      { label: 'D', text: '3.14 km/s' },
    ],
    correctAnswer: 'A',
    hint: 'v_o = √(g R) with g ≈ 9.8 m/s² and R ≈ 6.4 × 10⁶ m.',
    explanation: 'v_o = √(g R) = √(9.8 · 6.4 × 10⁶) = √(6.272 × 10⁷) ≈ 7.92 × 10³ m/s = 7.92 km/s.',
    conceptTested: 'First cosmic velocity / near-Earth orbital speed',
  },
  {
    id: 'q-sat-02',
    category: 'cat-08',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'For a satellite of mass m revolving in a circular orbit of radius r around a planet of mass M, its total mechanical energy E is related to its kinetic energy K by:',
    options: [
      { label: 'A', text: 'E = K' },
      { label: 'B', text: 'E = - K' },
      { label: 'C', text: 'E = 2 K' },
      { label: 'D', text: 'E = - 2 K' },
    ],
    correctAnswer: 'B',
    hint: 'K = + GMm / (2r) and U = - GMm / r. Add them: E = K + U.',
    explanation: 'K = 1/2 m v_o² = GMm / (2r)\nU = - GMm / r\nE = K + U = GMm/(2r) - GMm/r = - GMm / (2r) = - K.\nThe total energy is negative, representing a gravitationally bound orbit.',
    conceptTested: 'Energy partitioning in circular gravitational orbits',
  },
  {
    id: 'q-sat-03',
    category: 'cat-08',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'A geostationary satellite appears stationary above a fixed point on Earth’s equator. Its orbital period and direction of revolution are:',
    options: [
      { label: 'A', text: '12 hours, East to West' },
      { label: 'B', text: '24 hours, West to East' },
      { label: 'C', text: '24 hours, East to West' },
      { label: 'D', text: '84.6 minutes, North to South' },
    ],
    correctAnswer: 'B',
    hint: 'Earth rotates from West to East with a sidereal period of 24 hours.',
    explanation: 'To maintain a stationary position relative to Earth’s surface, a geostationary satellite must orbit in the equatorial plane with an orbital period of exactly 24 hours, moving from West to East.',
    conceptTested: 'Geostationary satellite orbit characteristics',
  },
  {
    id: 'q-sat-04',
    category: 'cat-08',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'What is the approximate orbital radius r and altitude h of a geostationary satellite above Earth’s surface? (Earth radius R ≈ 6400 km).',
    options: [
      { label: 'A', text: 'r ≈ 42,000 km, h ≈ 36,000 km' },
      { label: 'B', text: 'r ≈ 36,000 km, h ≈ 30,000 km' },
      { label: 'C', text: 'r ≈ 20,000 km, h ≈ 14,000 km' },
      { label: 'D', text: 'r ≈ 64,000 km, h ≈ 58,000 km' },
    ],
    correctAnswer: 'A',
    hint: 'T² = 4π²r³ / (GM) with T = 86,400 s. Solve for r, then h = r - R.',
    explanation: 'r = [ (GM · T²) / (4π²) ]^(1/3) ≈ 4.22 × 10⁷ m = 42,200 km ≈ 6.6 R_E.\nAltitude h = r - R ≈ 42,200 - 6,400 ≈ 35,800 km ≈ 36,000 km.',
    conceptTested: 'Geostationary orbital radius and altitude determination',
  },
  {
    id: 'q-sat-05',
    category: 'cat-08',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'What is the work done by the gravitational force on a satellite during one complete circular revolution around the Earth?',
    options: [
      { label: 'A', text: 'Zero' },
      { label: 'B', text: '2π · GMm / r' },
      { label: 'C', text: 'GMm / r²' },
      { label: 'D', text: '1/2 m v²' },
    ],
    correctAnswer: 'A',
    hint: 'In a circular orbit, what is the angle between gravitational force F⃗ and velocity vector v⃗?',
    explanation: 'In a circular orbit, the gravitational force acts radially inward (centripetal), while instantaneous velocity is strictly tangential. Because F⃗ ⊥ v⃗ (angle 90°) at every instant, work done W = ∫ F⃗·dr⃗ = 0.',
    conceptTested: 'Perpendicularity of central force and instantaneous velocity in circular motion',
  },
  {
    id: 'q-sat-06',
    category: 'cat-08',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'Two satellites S₁ and S₂ of masses m and 2m revolve around Earth in circular orbits of radii r₁ = R and r₂ = 4R respectively. The ratio of their orbital speeds v₁ / v₂ is:',
    options: [
      { label: 'A', text: '1 : 2' },
      { label: 'B', text: '2 : 1' },
      { label: 'C', text: '1 : 4' },
      { label: 'D', text: '4 : 1' },
    ],
    correctAnswer: 'B',
    hint: 'Orbital speed is v_o = √(GM/r), which is independent of satellite mass.',
    explanation: 'v_o = √(GM / r) ⟹ v₁ / v₂ = √(r₂ / r₁) = √(4R / R) = √4 = 2 / 1 = 2 : 1.\nNotice satellite mass has zero influence on orbital velocity.',
    conceptTested: 'Inverse square root relation between orbital velocity and radius',
  },
  {
    id: 'q-sat-07',
    category: 'cat-08',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'What is the orbital period T of a satellite revolving in a circular orbit grazing the surface of Earth? (Take R = 6400 km, g = 9.8 m/s²).',
    options: [
      { label: 'A', text: '42.3 minutes' },
      { label: 'B', text: '84.6 minutes' },
      { label: 'C', text: '120.0 minutes' },
      { label: 'D', text: '24.0 hours' },
    ],
    correctAnswer: 'B',
    hint: 'T = 2π √(R / g) = 2π √(6.4 × 10⁶ / 9.8).',
    explanation: 'T = 2π √(R / g) = 2 · 3.1416 · √(6.4 × 10⁶ / 9.8) ≈ 6.283 · 808.1 s ≈ 5078 s ≈ 84.6 minutes (~1.41 hours).',
    conceptTested: 'Orbital period of near-Earth satellite',
  },
  {
    id: 'q-sat-08',
    category: 'cat-08',
    examLevel: 'JEE MAIN',
    difficulty: 'HARD',
    type: 'trap',
    question: 'An artificial satellite in low Earth orbit experiences a tiny atmospheric drag force. Counter-intuitively, over time as the satellite spirals inward, its orbital speed v_o:',
    options: [
      { label: 'A', text: 'Decreases continuously until impact' },
      { label: 'B', text: 'Increases continuously' },
      { label: 'C', text: 'Remains strictly constant' },
      { label: 'D', text: 'Becomes zero immediately' },
    ],
    correctAnswer: 'B',
    hint: 'As radius r decreases due to drag, what happens to orbital speed v_o = √(GM/r)?',
    explanation: 'This is the "satellite paradox". As drag removes energy, orbital radius r decreases. Potential energy decreases by twice as much as mechanical energy is lost (ΔU = 2ΔE), and the surplus goes into kinetic energy (ΔK = -ΔE > 0). Hence, orbital speed v_o = √(GM/r) actually INCREASES as it spirals inward!',
    conceptTested: 'Satellite paradox: speed increase due to atmospheric drag',
  },
  {
    id: 'q-sat-09',
    category: 'cat-08',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Polar satellites orbit at relatively low altitudes (~500 to 800 km) passing over the north and south poles. What is their primary advantage?',
    options: [
      { label: 'A', text: 'They remain stationary over one country' },
      { label: 'B', text: 'As Earth rotates beneath them, they can scan every part of Earth’s surface strip by strip' },
      { label: 'C', text: 'They have zero orbital velocity' },
      { label: 'D', text: 'They require no rocket fuel for launch' },
    ],
    correctAnswer: 'B',
    hint: 'Earth spins West to East while the satellite orbits North to South.',
    explanation: 'Because the satellite orbits in a north-south plane while Earth rotates west-to-east underneath, the satellite scans successive longitudinal strips of Earth on each orbit, providing complete global coverage for remote sensing and weather forecasting.',
    conceptTested: 'Orbital geometry and utility of polar sun-synchronous satellites',
  },
  {
    id: 'q-sat-10',
    category: 'cat-08',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'A satellite of mass m is orbiting Earth in a circular orbit of radius r. How much additional energy must be supplied to transfer it into a higher circular orbit of radius 2r?',
    options: [
      { label: 'A', text: 'G M m / (2 r)' },
      { label: 'B', text: 'G M m / (4 r)' },
      { label: 'C', text: 'G M m / r' },
      { label: 'D', text: '3/4 G M m / r' },
    ],
    correctAnswer: 'B',
    hint: 'Total energy is E = -GMm/(2r). Calculate ΔE = E_final - E_initial.',
    explanation: 'E_initial = - GMm / (2r)\nE_final = - GMm / [ 2 · (2r) ] = - GMm / (4r)\nΔE = E_final - E_initial = - GMm / (4r) - ( - GMm / (2r) ) = GMm / (4r).\nSupplying +GMm/(4r) shifts the satellite to orbit 2r.',
    conceptTested: 'Orbital transfer energy calculation in circular orbits',
  },

  // =========================================================================
  // CATEGORY 09: KEPLER'S LAWS (10 Questions)
  // =========================================================================
  {
    id: 'q-kep-01',
    category: 'cat-09',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'According to Kepler’s First Law (Law of Orbits), the orbit of a planet around the Sun is an ellipse with the Sun situated at:',
    options: [
      { label: 'A', text: 'The exact geometric center of the ellipse' },
      { label: 'B', text: 'One of the two focal points of the ellipse' },
      { label: 'C', text: 'Both focal points simultaneously' },
      { label: 'D', text: 'The end of the minor axis' },
    ],
    correctAnswer: 'B',
    hint: 'An ellipse has two foci. Where does the attracting central mass sit?',
    explanation: 'Kepler’s First Law states: All planets move in elliptical orbits with the Sun positioned at one of the two foci of the ellipse.',
    conceptTested: "Kepler's First Law of Planetary Motion",
  },
  {
    id: 'q-kep-02',
    category: 'cat-09',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'Kepler’s Second Law (Law of Areas) states that the line joining the Sun and planet sweeps out equal areas in equal intervals of time. This law is a direct consequence of the conservation of:',
    options: [
      { label: 'A', text: 'Linear momentum' },
      { label: 'B', text: 'Mechanical energy' },
      { label: 'C', text: 'Angular momentum' },
      { label: 'D', text: 'Gravitational potential' },
    ],
    correctAnswer: 'C',
    hint: 'Torque τ = r⃗ × F⃗ = 0 for central forces. What conserved quantity does zero torque imply?',
    explanation: 'Because gravitational force is a central force directed toward the Sun, the torque about the Sun is zero: τ⃗ = r⃗ × F⃗ = 0. Zero torque implies conservation of angular momentum: L⃗ = r⃗ × p⃗ = constant. Areal velocity is dA/dt = L / (2m) = constant.',
    conceptTested: 'Conservation of angular momentum in Kepler’s Second Law',
  },
  {
    id: 'q-kep-03',
    category: 'cat-09',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'A planet moves in an elliptical orbit around the Sun. Its closest distance (perihelion) is r_p and farthest distance (aphelion) is r_a. What is the ratio of its orbital speeds v_p / v_a?',
    options: [
      { label: 'A', text: 'v_p / v_a = r_p / r_a' },
      { label: 'B', text: 'v_p / v_a = r_a / r_p' },
      { label: 'C', text: 'v_p / v_a = (r_a / r_p)²' },
      { label: 'D', text: 'v_p / v_a = √(r_a / r_p)' },
    ],
    correctAnswer: 'B',
    hint: 'At perihelion and aphelion, velocity is perpendicular to radius. Apply conservation of angular momentum: m·v_p·r_p = m·v_a·r_a.',
    explanation: 'By conservation of angular momentum:\nL = m · v_p · r_p = m · v_a · r_a\n⟹ v_p / v_a = r_a / r_p.\nThe planet moves fastest at perihelion and slowest at aphelion.',
    conceptTested: 'Perihelion to aphelion speed ratio from angular momentum conservation',
  },
  {
    id: 'q-kep-04',
    category: 'cat-09',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'numerical',
    question: 'A hypothetical planet is at an average distance from the Sun equal to 4 times the Earth’s average distance. According to Kepler’s Third Law, what is the planet’s period of revolution in Earth years?',
    options: [
      { label: 'A', text: '2 years' },
      { label: 'B', text: '4 years' },
      { label: 'C', text: '8 years' },
      { label: 'D', text: '16 years' },
    ],
    correctAnswer: 'C',
    hint: 'T² ∝ a³. If a = 4, calculate T = (4³)^(1/2) = (64)^(1/2).',
    explanation: 'By Kepler’s Third Law: (T_p / T_E)² = (a_p / a_E)³\n(T_p / 1)² = (4)³ = 64\nT_p = √64 = 8 Earth years.',
    conceptTested: "Kepler's Third Law (Harmonic Law) numerical application",
  },
  {
    id: 'q-kep-05',
    category: 'cat-09',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'If the semi-major axis of a planet’s orbit is 9 AU (where 1 AU is Earth’s orbital distance), its orbital period around the Sun is:',
    options: [
      { label: 'A', text: '18 years' },
      { label: 'B', text: '27 years' },
      { label: 'C', text: '81 years' },
      { label: 'D', text: '3 years' },
    ],
    correctAnswer: 'B',
    hint: 'T = a^(3/2) = (9)^(3/2) = (√9)³.',
    explanation: 'T² ∝ a³ ⟹ T = a^(3/2) = (9)^(3/2) = (3)³ = 27 Earth years.',
    conceptTested: 'Kepler’s Third Law scaling with fractional exponent',
  },
  {
    id: 'q-kep-06',
    category: 'cat-09',
    examLevel: 'CLASS 11-12',
    difficulty: 'EASY',
    type: 'conceptual',
    question: 'A planet is moving in an eccentric elliptical orbit around the Sun. Which of the following physical quantities remains strictly CONSTANT throughout its orbit?',
    options: [
      { label: 'A', text: 'Orbital speed v' },
      { label: 'B', text: 'Gravitational force F' },
      { label: 'C', text: 'Angular momentum L about the Sun' },
      { label: 'D', text: 'Kinetic energy K' },
    ],
    correctAnswer: 'C',
    hint: 'Torque about the Sun is zero.',
    explanation: 'Because distance r varies continuously in an ellipse, speed v, force F, and kinetic energy K all vary. However, because torque about the Sun is zero (τ = 0), the orbital angular momentum L is strictly conserved.',
    conceptTested: 'Invariance of angular momentum in Keplerian orbits',
  },
  {
    id: 'q-kep-07',
    category: 'cat-09',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'numerical',
    question: 'Halley’s comet has a highly eccentric orbit with perihelion distance r_p = 0.6 AU and aphelion distance r_a = 35.4 AU. What is the semi-major axis a of its orbit?',
    options: [
      { label: 'A', text: '18.0 AU' },
      { label: 'B', text: '17.7 AU' },
      { label: 'C', text: '36.0 AU' },
      { label: 'D', text: '34.8 AU' },
    ],
    correctAnswer: 'A',
    hint: 'Major axis is 2a = r_p + r_a. Divide by 2.',
    explanation: 'Major axis length: 2a = r_p + r_a = 0.6 + 35.4 = 36.0 AU.\nSemi-major axis: a = 36.0 / 2 = 18.0 AU.\n(Its orbital period is T = 18^(3/2) ≈ 76 years).',
    conceptTested: 'Orbital geometry of eccentric comets',
  },
  {
    id: 'q-kep-08',
    category: 'cat-09',
    examLevel: 'JEE MAIN',
    difficulty: 'MEDIUM',
    type: 'conceptual',
    question: 'In Kepler’s Third Law T² = K · a³, the proportionality constant K is equal to:',
    options: [
      { label: 'A', text: '4π² / (G M_sun)' },
      { label: 'B', text: 'G M_sun / (4π²)' },
      { label: 'C', text: '2π / (G M_sun)' },
      { label: 'D', text: '4π² G / M_sun' },
    ],
    correctAnswer: 'A',
    hint: 'Equate centripetal force m·ω²·r to gravitational force G·M·m/r² with ω = 2π/T.',
    explanation: 'm · (2π / T)² · r = G M m / r²\n4π² / T² = G M / r³\nT² = [ 4π² / (G M) ] · r³.\nHence the constant is K = 4π² / (G M_sun), identical for all planets orbiting the same central star.',
    conceptTested: 'Universal Keplerian proportionality constant',
  },
  {
    id: 'q-kep-09',
    category: 'cat-09',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'trap',
    question: 'If the gravitational attraction between two masses had varied as 1 / r³ (instead of 1 / r²), Kepler’s Third Law relating orbital period T and circular radius r would have been:',
    options: [
      { label: 'A', text: 'T² ∝ r²' },
      { label: 'B', text: 'T² ∝ r³' },
      { label: 'C', text: 'T² ∝ r⁴' },
      { label: 'D', text: 'T² ∝ r⁵' },
    ],
    correctAnswer: 'C',
    hint: 'm·ω²·r = G·M·m / r³. Solve for ω² and substitute ω = 2π/T.',
    explanation: 'm · (4π² / T²) · r = G M m / r³\n4π² / T² = G M / r⁴\nT² ∝ r⁴.\nIn general, for a central force F ∝ 1/r^n, T² ∝ r^(n+1). For n = 3, T² ∝ r⁴.',
    conceptTested: 'Generalized Kepler’s Third Law for non-standard power-law forces',
  },
  {
    id: 'q-kep-10',
    category: 'cat-09',
    examLevel: 'JEE ADVANCED',
    difficulty: 'HARD',
    type: 'numerical',
    question: 'An artificial satellite orbits in an ellipse of eccentricity e = 0.5. What is the ratio of its maximum kinetic energy K_max (at perihelion) to minimum kinetic energy K_min (at aphelion)?',
    options: [
      { label: 'A', text: '3 : 1' },
      { label: 'B', text: '9 : 1' },
      { label: 'C', text: '4 : 1' },
      { label: 'D', text: '2 : 1' },
    ],
    correctAnswer: 'B',
    hint: 'r_p = a(1 - e) and r_a = a(1 + e). By angular momentum, v_p / v_a = r_a / r_p. Kinetic energy ratio is (v_p / v_a)²',
    explanation: 'r_p = a(1 - e) = a(1 - 0.5) = 0.5 a\nr_a = a(1 + e) = a(1 + 0.5) = 1.5 a\nv_p / v_a = r_a / r_p = 1.5 / 0.5 = 3.\nKinetic energy ratio: K_max / K_min = (v_p / v_a)² = 3² = 9 : 1.',
    conceptTested: 'Kinetic energy variation in eccentric elliptical orbits',
  },

  // =========================================================================
  // CATEGORY 10: ADVANCED / JEE TRAPS (10 Questions)
  // =========================================================================
  {
    id: 'q-trap-01',
    category: 'cat-10',
    examLevel: 'JEE ADVANCED',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A smooth straight tunnel is drilled through the Earth passing directly through its center. A ball of mass m is dropped into the tunnel from the surface. The motion executed by the ball is:',
    options: [
      { label: 'A', text: 'Continuous acceleration until it strikes the opposite side at escape velocity' },
      { label: 'B', text: 'Simple Harmonic Motion with time period T = 2π √(R / g) ≈ 84.6 minutes' },
      { label: 'C', text: 'It comes to rest permanently at the center of the Earth' },
      { label: 'D', text: 'Periodic motion but not simple harmonic' },
    ],
    correctAnswer: 'B',
    hint: 'At distance x from center, restoring force is F = -m·g(x) = -(m·g/R)·x. What type of motion has restoring force F = -kx?',
    explanation: 'Inside Earth, g(x) = (g/R)·x directed toward the center.\nRestoring force: F = - (m g / R) · x = - k x, which is the exact equation of Simple Harmonic Motion (SHM).\nAngular frequency: ω = √(k/m) = √(g / R).\nTime period: T = 2π / ω = 2π √(R / g) ≈ 84.6 minutes.',
    conceptTested: 'Simple Harmonic Motion inside a tunnel drilled through Earth',
  },
  {
    id: 'q-trap-02',
    category: 'cat-10',
    examLevel: 'JEE ADVANCED',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A spherical cavity of radius R₁ is carved out inside a uniform solid sphere of radius R and density ρ. What is the nature of the gravitational field intensity g⃗ INSIDE the cavity?',
    options: [
      { label: 'A', text: 'Zero everywhere inside the cavity' },
      { label: 'B', text: 'Radial pointing toward the center of the cavity' },
      { label: 'C', text: 'Completely uniform in both magnitude and direction' },
      { label: 'D', text: 'Varies inversely with distance from the cavity wall' },
    ],
    correctAnswer: 'C',
    hint: 'Use superposition: g⃗_cavity = g⃗_full - g⃗_removed. Note that g⃗ = (4/3)πGρ·r⃗.',
    explanation: 'Let center of sphere be O and center of cavity be C with vector O⃗C = d⃗.\nAt any point P inside cavity: g⃗_full = (4/3)π G ρ · r⃗_P, and g⃗_removed = (4/3)π G ρ · (r⃗_P - d⃗).\nNet field: g⃗_cavity = g⃗_full - g⃗_removed = (4/3)π G ρ · d⃗.\nBecause d⃗ is a constant vector, the gravitational field inside the cavity is strictly UNIFORM in magnitude and direction!',
    conceptTested: 'Uniformity of gravitational field inside a spherical cavity',
  },
  {
    id: 'q-trap-03',
    category: 'cat-10',
    examLevel: 'JEE ADVANCED',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'Two identical stars, each of mass M, revolve around their common center of mass in a binary circular orbit of diameter d under mutual gravitational attraction. The period of revolution T is:',
    options: [
      { label: 'A', text: '2π · √(d³ / (G M))' },
      { label: 'B', text: '2π · √(d³ / (2 G M))' },
      { label: 'C', text: '2π · √(d³ / (4 G M))' },
      { label: 'D', text: 'π · √(d³ / (G M))' },
    ],
    correctAnswer: 'B',
    hint: 'Mutual distance is d. Radius of circular orbit for each star about center of mass is r = d/2.',
    explanation: 'Mutual gravitational force: F = G M² / d².\nThis provides centripetal force for orbit of radius r = d/2:\nM · ω² · (d / 2) = G M² / d²\nω² = 2 G M / d³ ⟹ ω = √(2 G M / d³).\nT = 2π / ω = 2π √(d³ / (2 G M)).',
    conceptTested: 'Binary star orbital dynamics and center of mass motion',
  },
  {
    id: 'q-trap-04',
    category: 'cat-10',
    examLevel: 'JEE ADVANCED',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A mass m is taken slowly from the surface of Earth to infinity. What is the work done by the GRAVITATIONAL FORCE of the Earth?',
    options: [
      { label: 'A', text: '+ m g R' },
      { label: 'B', text: '- m g R' },
      { label: 'C', text: '+ 1/2 m g R' },
      { label: 'D', text: '- 1/2 m g R' },
    ],
    correctAnswer: 'B',
    hint: 'Gravity pulls inward while displacement is outward. What is the sign of W_gravity?',
    explanation: 'Work done by gravitational force: W_g = - ΔU = - [ U(∞) - U(R) ] = - [ 0 - (-GMm/R) ] = - GMm / R = - m g R.\n(Note: Work done by the EXTERNAL agent is +mgR, but work done by GRAVITY is strictly negative because force opposes displacement).',
    conceptTested: 'Sign convention: work done by gravity vs external agent',
  },
  {
    id: 'q-trap-05',
    category: 'cat-10',
    examLevel: 'JEE MAIN',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A student claims: "Since g⃗ = - (GM/r²) r̂ has a minus sign, the magnitude of gravitational field intensity is negative." What is the error in this statement?',
    options: [
      { label: 'A', text: 'Magnitude is a norm |g⃗| = GM/r² which is strictly non-negative; the minus sign belongs to the direction vector -r̂' },
      { label: 'B', text: 'The formula is wrong and has no minus sign' },
      { label: 'C', text: 'G is negative, so two negatives make it positive' },
      { label: 'D', text: 'Field is scalar so it cannot have direction' },
    ],
    correctAnswer: 'A',
    hint: 'Vector magnitudes |v⃗| are always non-negative numbers representing length or strength.',
    explanation: 'In vector algebra, vector magnitude |g⃗| is defined as the absolute norm and is strictly non-negative: |g⃗| = GM/r² ≥ 0. The minus sign represents direction: (-r̂) indicates that the field vector points inward toward the source mass.',
    conceptTested: 'Distinction between vector direction sign and scalar magnitude',
  },
  {
    id: 'q-trap-06',
    category: 'cat-10',
    examLevel: 'JEE ADVANCED',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A body is projected vertically from Earth’s surface with speed v = 0.5 v_e (half of escape velocity). What is the maximum height h reached above Earth’s surface in terms of Earth’s radius R?',
    options: [
      { label: 'A', text: 'h = R / 4' },
      { label: 'B', text: 'h = R / 3' },
      { label: 'C', text: 'h = R / 2' },
      { label: 'D', text: 'h = 3 R' },
    ],
    correctAnswer: 'B',
    hint: '1/2 m v² - GMm/R = -GMm/(R+h). Substitute v² = 1/4 v_e² = 1/4 (2GM/R) = GM/(2R).',
    explanation: 'Kinetic energy at surface: K = 1/2 m (v_e / 2)² = 1/8 m v_e² = 1/8 m (2GM/R) = GMm / (4R).\nConservation of energy:\nGMm / (4R) - GMm / R = - GMm / (R + h)\n- 3/4 · (GMm / R) = - GMm / (R + h)\n3 / (4R) = 1 / (R + h) ⟹ 3(R + h) = 4R ⟹ 3R + 3h = 4R ⟹ 3h = R ⟹ h = R / 3.',
    conceptTested: 'Exact non-linear height reached by high-velocity projectile',
  },
  {
    id: 'q-trap-07',
    category: 'cat-10',
    examLevel: 'JEE ADVANCED',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A thin spherical shell of mass M and radius R has a concentric smaller spherical shell of mass m and radius r (r < R). What is the gravitational force on mass m due to shell M?',
    options: [
      { label: 'A', text: 'G M m / (R - r)²' },
      { label: 'B', text: 'G M m / R²' },
      { label: 'C', text: 'Strictly Zero' },
      { label: 'D', text: 'G M m / r²' },
    ],
    correctAnswer: 'C',
    hint: 'The inner shell lies entirely inside the outer shell.',
    explanation: 'By Shell Theorem, the gravitational field inside a uniform spherical shell of mass M is zero everywhere. Because the inner shell of mass m resides completely in this zero-field region, the net force exerted on it by shell M is strictly zero.',
    conceptTested: 'Shell Theorem application to concentric spherical shells',
  },
  {
    id: 'q-trap-08',
    category: 'cat-10',
    examLevel: 'JEE MAIN',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A pendulum clock that keeps accurate time on Earth’s surface is taken to a high mountain. Will it gain or lose time, and why?',
    options: [
      { label: 'A', text: 'It gains time because g is larger' },
      { label: 'B', text: 'It loses time (runs slow) because g decreases with altitude' },
      { label: 'C', text: 'It keeps the exact same time because period is independent of g' },
      { label: 'D', text: 'It stops oscillating completely' },
    ],
    correctAnswer: 'B',
    hint: 'Pendulum period is T = 2π √(L / g). If g decreases, what happens to T?',
    explanation: 'Time period of a simple pendulum is T = 2π √(L / g). On a mountain, g is smaller. As g decreases, T increases, meaning each tick takes longer. Therefore, the clock loses time (runs slow).',
    conceptTested: 'Effect of altitude gravity variation on simple pendulum period',
  },
  {
    id: 'q-trap-09',
    category: 'cat-10',
    examLevel: 'JEE ADVANCED',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A particle is released from rest at a distance 2R from the center of a fixed uniform solid sphere of radius R and mass M. With what speed does it strike the surface of the sphere?',
    options: [
      { label: 'A', text: '√(G M / R)' },
      { label: 'B', text: '√(2 G M / R)' },
      { label: 'C', text: '√(G M / (2 R))' },
      { label: 'D', text: '2 √(G M / R)' },
    ],
    correctAnswer: 'A',
    hint: 'Apply mechanical energy conservation: 0 - GMm/(2R) = 1/2 m v² - GMm/R.',
    explanation: 'Initial energy: E_i = - GMm / (2R).\nFinal energy at surface: E_f = 1/2 m v² - GMm / R.\nBy conservation of energy:\n1/2 m v² - GMm / R = - GMm / (2R)\n1/2 m v² = GMm / R - GMm / (2R) = GMm / (2R)\nv² = G M / R ⟹ v = √(G M / R).',
    conceptTested: 'Impact speed of body falling from rest in astronomical gravity',
  },
  {
    id: 'q-trap-10',
    category: 'cat-10',
    examLevel: 'JEE ADVANCED',
    difficulty: 'JEE TRAP',
    type: 'trap',
    question: 'A uniform ring of mass M and radius R has a point mass m placed on its axis at distance x = R√3 from its center. What is the gravitational attraction between the ring and the point mass?',
    options: [
      { label: 'A', text: '√3 / 8 · (G M m / R²)' },
      { label: 'B', text: '3 / 8 · (G M m / R²)' },
      { label: 'C', text: '√3 / 4 · (G M m / R²)' },
      { label: 'D', text: 'G M m / (4 R²)' },
    ],
    correctAnswer: 'A',
    hint: 'Axial field of a ring is g = G M x / (R² + x²)^(3/2). Substitute x = R√3.',
    explanation: 'Field on ring axis: g = G M x / (R² + x²)^(3/2).\nWith x = R√3:\nR² + x² = R² + 3R² = 4R².\n(R² + x²)^(3/2) = (4R²)^(3/2) = 8 R³.\nForce F = m · g = G M m · (R√3) / (8 R³) = (√3 / 8) · (G M m / R²).',
    conceptTested: 'Axial gravitational attraction of a continuous mass ring',
  },
]
